### ISSUE TITLE
Please explain in detail how the extracted frames of the extract_frame.py file are saved.

### ISSUE THREAD

**Issue by Jerry-ji0501** [Iriya99/OVRE#1]
I'm sorry to bother that  i was encountering difficulty in extracting the raw videos into frames.  Does it extract frames from each category of video and save them in the corresponding video category? Or does it save all videos according to their vidx? I'm sorry that I don't understand it specifically from the code. I hope you can provide some help.

**Comment by Jerry-ji0501** [comment]
I have got the 365 raw videos from MMT. And put it as the video under the ./data 
But for the extracted_frame.py, if i set the src = './data/videos/ ' dst = './data/image/'  , i can't  extract the frame for the folder. Logically, the src here should be the folder name where .mp4 is located. However, if I traverse the 365 subfolders under video and then use it as src, I don’t know whether I should mkdir 365 subfolders under image and save frame accordingly.

**Comment by Iriya99** [comment]
> I have got the 365 raw videos from MMT. And put it as the video under the ./data But for the extracted_frame.py, if i set the src = './data/videos/ ' dst = './data/image/' , i can't extract the frame for the folder. Logically, the src here should be the folder name where .mp4 is located. However, if I traverse the 365 subfolders under video and then use it as src, I don’t know whether I should mkdir 365 subfolders under image and save frame accordingly.

Yes, src is the directory where the video is located, and after executing load_frames_from_video function, each video will generate a directory under dst.
