### ISSUE TITLE
关于视频抽帧的一些问题

### ISSUE THREAD

**Issue by zhaoyangwei123** [Iriya99/OVRE#2]
您好，非常感谢您的工作，但是我在您的抽帧代码里看到您似乎对视频进行一秒钟30帧的高频率抽帧，请问这么高频率的抽帧是为什么呢，一般来说一秒的视频即使是动态较高的话抽5帧已经很多了，您抽这么多帧有什么其他的优势吗？

**Comment by Iriya99** [comment]
我觉得抽少一些也可以，没有特别大的影响



在 2024-09-01 19:49:51，"Wei Zhaoyang" ***@***.***> 写道：

您好，非常感谢您的工作，但是我在您的抽帧代码里看到您似乎对视频进行一秒钟30帧的高频率抽帧，请问这么高频率的抽帧是为什么呢，一般来说一秒的视频即使是动态较高的话抽5帧已经很多了，您抽这么多帧有什么其他的优势吗？

**Comment by Iriya99** [comment]
我觉得少抽一些帧也可以，毕竟最后输入模型的是8/16帧，而且MMIT的视频本身就很短
